### ISSUE TITLE
create a web UI

### ISSUE THREAD

**Issue by m-adawi** [m-adawi/swarm-cd#16]
Create a web UI to show deployment status for each stack and display errors, if any. Other features:

- show stack service replicas
- sync button for manual updates
- search bar to filter stacks 
- show stack compose and config files

**Comment by Fleury93** [comment]
What approach, lang or framework do you plan to use it? Maybe I can help you with that. Go I think is not the best choice for this issue. What do you think?

**Comment by m-adawi** [comment]
@Fleury93 Thanks for offering your help! @EhabY is planning to use React for the frontend, and he will push some changes soon. However, any further help or contributions from you would be greatly appreciated as we move forward.

**Comment by Fleury93** [comment]
Afterwards, maybe some management features can be added like in Portainer or Swarmpit. Or read only info at least. Like nodes in swarm, networks, and volumes. Resource usage as well. 

Do you plan this?

**Comment by m-adawi** [comment]
This tool wasn't intended for swarm management but I might implement some of these features like showing resource usage and services and their running containers' status
