### ISSUE TITLE
sops_files type detection not working

### ISSUE THREAD

**Issue by sanzoghenzo** [m-adawi/swarm-cd#27]
Hi there, I started to push secrets to my repository, and at first everythong went well since I only used binary files.

Now that I pushed a yaml file, I got a decrypt error:

```
evel=ERROR msg="failed to decrypt one or more sops files for authentik stack: could not decrypt the file repos/swarm-ops/stacks/authentik/secrets/systra-ad-source.yaml: Error unmarshalling input json: invalid character '-' in numeric literal"
```

The `input json` got me thinking, and I could reproduce the error locally if i forced the `--input-type` to `json` or `binary`.

Looking at the source code, the `sops.getFileFormat` function uses `filepath.Ext` that returns the extension with the leading dot, but the output variable is compared to literals without the dot.

I'm pushing a PR to fix this soon

**Comment by m-adawi** [comment]
> I'm pushing a PR to fix this soon
Thanks for your contribution
