### ISSUE TITLE
how to handle secrets

### ISSUE THREAD

**Issue by sanzoghenzo** [m-adawi/swarm-cd#6]
Hi there!
First of all, thanks for this gem, it is just what I was looking for these days (after ruling out k8s for being too overkill for my use cases)!

This is more of an open question than an issue, but how would you manage the secrets to be passed to the stacks deployed via swarm-cd?

For swarm-cd itself I can use swarm secrets to store the repos.yaml file and don't commit it to git.
The only way I see is to manually create the secrets and specify them in the compose file as external, but this defeats the gitops paradigm since I would need to access the swarm as a user instead of relying on git rbac

Any thoughts on this?

**Comment by m-adawi** [comment]
Hi @sanzoghenzo

> First of all, thanks for this gem, it is just what I was looking for these days

Thanks for your support.

> This is more of an open question than an issue, but how would you manage the secrets to be passed to the stacks deployed via swarm-cd?

This is actually a problem that I have been thinking about. For Kubernetes, we have all the fancy secret management tools like External Secrets Operator, Sealed Secrets and more. But I couldn't find something similar for Swarm. 

Maybe we can use something like [sops](https://github.com/getsops/sops) or [git-crypt](https://github.com/AGWA/git-crypt). These tools allow us to encrypt secrets in a git repo and be able to decrypt them after we pull. But I might have to add support to them in SwarmCD, maybe by making it execute some commands after pull. This way we only need to create a docker secret for the decryption key manually, and the other keys will be decrypted automatically after pull. What do you think?

**Comment by m-adawi** [comment]
> I don't know if it could help, but I see that there's [the decrypt go library](https://pkg.go.dev/github.com/getsops/sops/v3/decrypt) for in-process SOPS files decryption.

I was actually testing this library just now and I think I will go with it. The file `stacks.yaml` should look something like this:

```yaml
stack:
  repo: repo-name
  branch: branch-name
  compose_file: compose-file.yaml
  sops_files:
    - secrets/secret1.txt
    - secrets/secret2.txt
```
It should pull the repo, decrypt the files under `sops_files` and deploy/update the stack. The user needs to set the needed SOPS environment variables in SwarmCD deployment stack file or an env_file

**Comment by sanzoghenzo** [comment]
I don't know if it is of any interest, but I found [this article](https://blog.viktoradam.net/2018/02/28/swarm-secrets-made-easy/) that offers a way to change the secrets without having to remove/rename them manually.

It uses the `name` attribute of a secret/config to append the md5 of the file to it via environment variables, so that they are renamed only when changed.
As you can see in the comment, I've replicated the automation using yq, awk and other bash commands, and used a different schema for the variables (`<SECRET_NAME>_MD5`), but I suppose this is useless since you can do everything directly in go.
The name could be directly set in the manifest before deploying it, skipping the need for environment/shell variables.

**Comment by m-adawi** [comment]
v1.1.0 with released with SOPS support

**Comment by m-adawi** [comment]
> I don't know if it is of any interest, but I found [this article](https://blog.viktoradam.net/2018/02/28/swarm-secrets-made-easy/) that offers a way to change the secrets without having to remove/rename them manually.

Thanks for sharing this. I will open a new issue to support this

**Comment by m-adawi** [comment]
I opened #11

**Comment by m-adawi** [comment]
I'm closing this now. If someone wants to discuss other methods of managing secrets they can open a new issue
