### ISSUE TITLE
Crash when stack refers to a non-existing repo

### ISSUE THREAD

**Issue by sanzoghenzo** [m-adawi/swarm-cd#8]
I mistakenly used a different name for my my repo inside one of my stack, and I got this in return

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1174aba]

goroutine 1 [running]:
main.initStacks(...)
    /go/init.go:70
main.init.0()
    /go/init.go:27 +0x15a
```

Using latest docker version, I see that you've moved things around but the [issue is still there](https://github.com/m-adawi/swarm-cd/blob/main/swarmcd/init.go#L65): there's no check of `stackConfig.Repo` key being present in `config.RepoConfigs`.

**Comment by m-adawi** [comment]
Fixed in #9. Now it will exit with a helpful error message
